"use client";

import { Epilogue } from "next/font/google";
import "./globals.css";
import "primereact/resources/themes/saga-blue/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";

import HeaderWidget from "@widgets/common/HeaderWidget";
import StyledComponentsRegistry from "./lib/registry";
import { RootContainer } from "./layout.styled";

// const inter = Inter({ subsets: ["latin"] });
const epilogue = Epilogue({ subsets: ["latin"] }); // Epilogue is a Google Font
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <StyledComponentsRegistry>
        <body className={epilogue.className}>
          <RootContainer id='container'>
            <HeaderWidget />
            {children}
          </RootContainer>
        </body>
      </StyledComponentsRegistry>
    </html>
  );
}
